[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install fastapi uvicorn httpx pydantic==1.10.9 --break-system-packages"]

[start]
cmd = "python main.py"
