/**
 * Corrections de statut issues de la feuille « CRM AURA FLOW AI »,
 * onglet « Liste de prospection », relue le 8 août 2026.
 *
 * Ce fichier est une **transcription**, pas une règle : chaque ligne porte le
 * numéro de la ligne source et la preuve qui a motivé la décision, pour qu'on
 * puisse la contester dans six mois sans rouvrir le tableur.
 *
 * La feuille reste en lecture seule — rien n'y a été écrit.
 *
 * Rapprochement : par adresse électronique, à défaut par nom + société. Cinq
 * lignes n'ont pas d'adresse ; elles sont marquées `uncertain` et le script les
 * signale au lieu de les appliquer en silence.
 */
export interface StatusCorrection {
  /** Ligne dans la feuille source. Sert à retrouver l'origine d'une décision. */
  readonly row: number;
  readonly firstName: string;
  readonly lastName: string;
  readonly email: string;
  readonly company: string;
  readonly lifecycle: "Perdu";
  readonly lostReason: string;
  /** Ce que dit la feuille. Repris tel quel dans l'interaction consignée. */
  readonly evidence: string;
}

export const STATUS_CORRECTIONS: readonly StatusCorrection[] = [
  {
    row: 22,
    firstName: "Marion",
    lastName: "Teuliere",
    email: "",
    company: "Soin de Soi",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 28,
    firstName: "Ridha",
    lastName: "Sahli",
    email: "",
    company: "Origine CBD",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 33,
    firstName: "Laeticia",
    lastName: "Martinez",
    email: "",
    company: "Skintips",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 35,
    firstName: "Antoine",
    lastName: "mignot",
    email: "antoine.mignot@labomai.com   lmeridji@labomaicom",
    company: "Activlong",
    lifecycle: "Perdu",
    lostReason: "Ne répond plus",
    evidence: "marqué « Pas de réponse » dans la feuille",
  },
  {
    row: 36,
    firstName: "jimmy",
    lastName: "guittonneau",
    email: "jimmy@beaute-insolente.com",
    company: "beaute insolente",
    lifecycle: "Perdu",
    lostReason: "Ne répond plus",
    evidence: "marqué « Pas de réponse » dans la feuille",
  },
  {
    row: 37,
    firstName: "",
    lastName: "",
    email: "assistante@divasfabulous.com",
    company: "Divasfabulous",
    lifecycle: "Perdu",
    lostReason: "Ne répond plus",
    evidence: "marqué « Pas de réponse » dans la feuille",
  },
  {
    row: 39,
    firstName: "Julie",
    lastName: "Docteur julie pernet",
    email: "julie@makemymask.com",
    company: "Make my mask",
    lifecycle: "Perdu",
    lostReason: "Ne répond plus",
    evidence: "marqué « Pas de réponse » dans la feuille",
  },
  {
    row: 40,
    firstName: "Camille",
    lastName: "pereira",
    email: "camille@medene.fr",
    company: "Medene",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 54,
    firstName: "Clément",
    lastName: "poyade",
    email: "clement.poyade@gmail.com",
    company: "Yacon & Co",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 55,
    firstName: "Jeanne",
    lastName: "rose gaston",
    email: "",
    company: "Hydrolite",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 75,
    firstName: "Elise",
    lastName: "postil",
    email: "elise.postil@twentydc.com",
    company: "Twenty dc",
    lifecycle: "Perdu",
    lostReason: "Pas le bon interlocuteur",
    evidence: "site Wix e-commerce — hors cible",
  },
  {
    row: 82,
    firstName: "Sylvain",
    lastName: "barraud",
    email: "sylvain.barraud@dynamiz.fr",
    company: "Dynamiz",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 86,
    firstName: "Damien",
    lastName: "Reny",
    email: "damien@hexa3.eu",
    company: "HEXA3",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 91,
    firstName: "Jean",
    lastName: "larmanjat",
    email: "jean@casyx.com",
    company: "Casyx",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 97,
    firstName: "Hugo",
    lastName: "Fachin",
    email: "facchin@visimitra.com",
    company: "Cuure",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 99,
    firstName: "Victor",
    lastName: "Montaucet",
    email: "",
    company: "Agence ads",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 100,
    firstName: "Nathalie",
    lastName: "Dabin",
    email: "nathalie.dabin@mademoisellecosmetique.com",
    company: "Laboratoire mademoiselle",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 114,
    firstName: "Claire",
    lastName: "leina",
    email: "claireleina@allthewaystosay.com",
    company: "All the way to say",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 118,
    firstName: "Carine",
    lastName: "bozon",
    email: "carine.bozon@aglaiaco.com",
    company: "aglaicao",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 120,
    firstName: "Laurent",
    lastName: "Pan",
    email: "partnership@secretdepeau.fr",
    company: "Skin cafeine",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 129,
    firstName: "Claire teixeira",
    lastName: "Claire",
    email: "claire@rosaeparis.com",
    company: "Roseaparis",
    lifecycle: "Perdu",
    lostReason: "Concurrent",
    evidence: "« Il ont déjà un chatbot mais générique »",
  },
  {
    row: 132,
    firstName: "Saskia",
    lastName: "slama",
    email: "saskia@pomad.paris",
    company: "Pomad",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 134,
    firstName: "Anne",
    lastName: "Querard",
    email: "anne@hozhoparis.com",
    company: "Hozhoparis",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 135,
    firstName: "Paul",
    lastName: "etienne jacob",
    email: "paul-etienne@epycure.com",
    company: "epycure",
    lifecycle: "Perdu",
    lostReason: "Ne répond plus",
    evidence: "marqué « Pas de réponse » dans la feuille",
  },
  {
    row: 137,
    firstName: "Gina ceku",
    lastName: "Gina ceku",
    email: "gina@carel.fr",
    company: "Carel paris",
    lifecycle: "Perdu",
    lostReason: "Ne répond plus",
    evidence: "marqué « Pas de réponse » dans la feuille",
  },
  {
    row: 138,
    firstName: "Estelle xie",
    lastName: "Estelle xie",
    email: "exie@inesdelafressange.fr",
    company: "Ines de la fressange",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 141,
    firstName: "Hanna",
    lastName: "Hanna",
    email: "hanna@march-lab.com",
    company: "Marchlab",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "refus explicite, aucun motif indiqué",
  },
  {
    row: 145,
    firstName: "Jessica",
    lastName: "patron ( recrutement)",
    email: "jessica@ams-beauty.com",
    company: "Ams beuty",
    lifecycle: "Perdu",
    lostReason: "Pas le bon interlocuteur",
    evidence: "interlocuteur recrutement, pas décisionnaire",
  },
  {
    row: 152,
    firstName: "Mickael",
    lastName: "fradin",
    email: "mike@nateev.fr",
    company: "Agence nateev",
    lifecycle: "Perdu",
    lostReason: "Pas intéressé",
    evidence: "« Pas interesse » en note libre",
  },
];
